---
on:
  push:
  pull_request:

name: Lints
jobs:
  eslint:
    name: ESLint
    runs-on: [self-hosted, light]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Cache node modules
        id: cache-dep
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install JS dependencies
        if: steps.cache-dep.outputs.cache-hit != 'true'
        run: npm install
      - name: Run prettier
        run: npx prettier --check src
      - name: Run ESLint
        run: npm run lint
